"""add_script_content_to_perf_test_scenario

Revision ID: 3e962718dc61
Revises: add_test_report_features
Create Date: 2026-01-03 19:18:20.639421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e962718dc61'
down_revision = 'add_test_report_features'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perf_test_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script_content', sa.Text(), nullable=True, comment='Locust 脚本内容'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perf_test_scenarios', schema=None) as batch_op:
        batch_op.drop_column('script_content')

    # ### end Alembic commands ###
